export default {
    STRING_EQUAL: "string_equal",
    STRING_STARTS_WITH: "string_starts_with",
    STRING_ENDS_WITH: "string_ends_with",
    STRING_CONTAINS: "string_contains",
    INT_RANGE: "int_range",
    ZIPCODE_EQUAL: "zipcode_equal",
    ZIPCODE_STARTS_WITH: "zipcode_starts_with",
    ZIPCODE_ENDS_WITH: "zipcode_ends_with",
    ZIPCODE_CONTAINS: "zipcode_contains",
    ZIPCODE_RANGE: "zipcode_range",
    UTM_EQUAL: "utm_equal",
    UTM_STARTS_WITH: "utm_starts_with",
    UTM_ENDS_WITH: "utm_ends_with",
    UTM_CONTAINS: "utm_contains",
    INDUSTRY_EQUAL: "industry_equal",
    INDUSTRY_STARTS_WITH: "industry_starts_with",
    INDUSTRY_ENDS_WITH: "industry_ends_with",
    INDUSTRY_CONTAINS: "industry_contains",
};
